
namespace Passwordless.BlazorWebAssembly.Tests.DataFactory;

public static class Data
{
    public const string BadRequestResponse = "\"Oops. Did I do that?\"";
    public const string ProblemDetailsResponse = "{\"type\":\"https://example.com/probs/out-of-credit\",\"title\":\"You do not have enough credit.\",\"detail\":\"Your current balance is 30, but that costs 50.\",\"instance\":\"/account/12345/msgs/abc\",\"balance\":30,\"accounts\":[\"/account/12345\",\"/account/67890\"]}";

    public const string ValidRegisterBeginRequest = "{\"token\":\"register_k8Qgxpd7MmnIZU1snSEiM923jwthaQuldE44VRtPVTprJ3bEotwAE9f_u_5-0GYbhTbZJDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMMDAwMDAwMDA2SQ5MjI0YzJhMS1kMzc0LTQ1ZDEtYjQ0Yi0yZDYzM2FhZjFiOGOvQWVnb24gVGFyZ2FyeWVutFBsYXlncm91bmQ6IGpvaG5zbm93pG5vbmXAw6lQcmVmZXJyZWSRqGpvaG5zbm93ws4PKdKS\",\"RPID\":\"admin.passwordless.dev\",\"Origin\":\"https://admin.passwordless.dev\"}";
    public const string ValidRegisterBeginResponse = "{\"data\":{\"rp\":{\"id\":\"admin.passwordless.dev\",\"name\":\"admin.passwordless.dev\"},\"user\":{\"name\":\"Playground: johnsnow\",\"id\":\"OTIyNGMyYTEtZDM3NC00NWQxLWI0NGItMmQ2MzNhYWYxYjhj\",\"displayName\":\"Aegon Targaryen\"},\"challenge\":\"jKQa7jMCiSis397AesiWew\",\"pubKeyCredParams\":[{\"type\":\"public-key\",\"alg\":-8},{\"type\":\"public-key\",\"alg\":-7},{\"type\":\"public-key\",\"alg\":-257},{\"type\":\"public-key\",\"alg\":-37},{\"type\":\"public-key\",\"alg\":-35},{\"type\":\"public-key\",\"alg\":-258},{\"type\":\"public-key\",\"alg\":-38},{\"type\":\"public-key\",\"alg\":-36},{\"type\":\"public-key\",\"alg\":-259},{\"type\":\"public-key\",\"alg\":-39}],\"timeout\":60000,\"attestation\":\"none\",\"authenticatorSelection\":{\"residentKey\":\"required\",\"requireResidentKey\":true,\"userVerification\":\"preferred\"},\"excludeCredentials\":[],\"extensions\":{\"credProps\":true},\"status\":\"ok\",\"errorMessage\":\"\"},\"session\":\"session_k8Qgyw8V1j25eqjAu-2zgdJUl5kFgnsOc4fcHni-7g1VfnvFAsaDp09wdGlvbnOLplN0YXR1c6Jva6xFcnJvck1lc3NhZ2WgolJwg6JJZLZhZG1pbi5wYXNzd29yZGxlc3MuZGV2pE5hbWW2YWRtaW4ucGFzc3dvcmRsZXNzLmRldqRJY29uwKRVc2Vyg6ROYW1ltFBsYXlncm91bmQ6IGpvaG5zbm93oklkxCQ5MjI0YzJhMS1kMzc0LTQ1ZDEtYjQ0Yi0yZDYzM2FhZjFiOGOrRGlzcGxheU5hbWWvQWVnb24gVGFyZ2FyeWVuqUNoYWxsZW5nZcQQjKQa7jMCiSis397AesiWe7BQdWJLZXlDcmVkUGFyYW1zmoKkVHlwZQCjQWxn-IKkVHlwZQCjQWxn-YKkVHlwZQCjQWxn0f7_gqRUeXBlAKNBbGfQ24KkVHlwZQCjQWxn0N2CpFR5cGUAo0FsZ9H-_oKkVHlwZQCjQWxn0NqCpFR5cGUAo0FsZ9DcgqRUeXBlAKNBbGfR_v2CpFR5cGUAo0FsZ9DZp1RpbWVvdXTN6mCrQXR0ZXN0YXRpb24AtkF1dGhlbnRpY2F0b3JTZWxlY3Rpb26Et0F1dGhlbnRpY2F0b3JBdHRhY2htZW50wKtSZXNpZGVudEtleQCyUmVxdWlyZVJlc2lkZW50S2V5w7BVc2VyVmVyaWZpY2F0aW9uAbJFeGNsdWRlQ3JlZGVudGlhbHOQqkV4dGVuc2lvbnOJp0V4YW1wbGXApUFwcElEwKpFeHRlbnNpb25zwLZVc2VyVmVyaWZpY2F0aW9uTWV0aG9kwKxEZXZpY2VQdWJLZXnAqUNyZWRQcm9wc8OjUFJGwLpDcmVkZW50aWFsUHJvdGVjdGlvblBvbGljecDZIUVuZm9yY2VDcmVkZW50aWFsUHJvdGVjdGlvblBvbGljecCnQWxpYXNlc5Goam9obnNub3esQWxpYXNIYXNoaW5nws4PKdKS\"}";
    public const string ValidRegisterCompleteRequest = "{\"session\":\"session_k8Qgyw8V1j25eqjAu-2zgdJUl5kFgnsOc4fcHni-7g1VfnvFAsaDp09wdGlvbnOLplN0YXR1c6Jva6xFcnJvck1lc3NhZ2WgolJwg6JJZLZhZG1pbi5wYXNzd29yZGxlc3MuZGV2pE5hbWW2YWRtaW4ucGFzc3dvcmRsZXNzLmRldqRJY29uwKRVc2Vyg6ROYW1ltFBsYXlncm91bmQ6IGpvaG5zbm93oklkxCQ5MjI0YzJhMS1kMzc0LTQ1ZDEtYjQ0Yi0yZDYzM2FhZjFiOGOrRGlzcGxheU5hbWWvQWVnb24gVGFyZ2FyeWVuqUNoYWxsZW5nZcQQjKQa7jMCiSis397AesiWe7BQdWJLZXlDcmVkUGFyYW1zmoKkVHlwZQCjQWxn-IKkVHlwZQCjQWxn-YKkVHlwZQCjQWxn0f7_gqRUeXBlAKNBbGfQ24KkVHlwZQCjQWxn0N2CpFR5cGUAo0FsZ9H-_oKkVHlwZQCjQWxn0NqCpFR5cGUAo0FsZ9DcgqRUeXBlAKNBbGfR_v2CpFR5cGUAo0FsZ9DZp1RpbWVvdXTN6mCrQXR0ZXN0YXRpb24AtkF1dGhlbnRpY2F0b3JTZWxlY3Rpb26Et0F1dGhlbnRpY2F0b3JBdHRhY2htZW50wKtSZXNpZGVudEtleQCyUmVxdWlyZVJlc2lkZW50S2V5w7BVc2VyVmVyaWZpY2F0aW9uAbJFeGNsdWRlQ3JlZGVudGlhbHOQqkV4dGVuc2lvbnOJp0V4YW1wbGXApUFwcElEwKpFeHRlbnNpb25zwLZVc2VyVmVyaWZpY2F0aW9uTWV0aG9kwKxEZXZpY2VQdWJLZXnAqUNyZWRQcm9wc8OjUFJGwLpDcmVkZW50aWFsUHJvdGVjdGlvblBvbGljecDZIUVuZm9yY2VDcmVkZW50aWFsUHJvdGVjdGlvblBvbGljecCnQWxpYXNlc5Goam9obnNub3esQWxpYXNIYXNoaW5nws4PKdKS\",\"response\":{\"id\":\"AltqnKLVfJmwvisFNfDMyah4Af5AsI99kRFbYaTPQVc\",\"rawId\":\"AltqnKLVfJmwvisFNfDMyah4Af5AsI99kRFbYaTPQVc\",\"type\":\"public-key\",\"extensions\":{\"credProps\":{\"rk\":true}},\"response\":{\"AttestationObject\":\"o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVik8egiesVpgMwlnLcY0N3ldtvrzKGUPb763GkSYC4CzTlFAAAAAHcbSP3T1E90kjL8FXqwUHoAIAJbapyi1XyZsL4rBTXwzMmoeAH-QLCPfZERW2Gkz0FXpQECAyYgASFYIK1vYF4G076YgpwpV0-uxM34PQWN9P40i7Dh0-lxtc85IlggeReXcNqqZPBvBvmSxGjXBIbjvQwQGbIatx34XLfQAdM\",\"clientDataJson\":\"eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiaktRYTdqTUNpU2lzMzk3QWVzaVdldyIsIm9yaWdpbiI6Imh0dHBzOi8vYWRtaW4ucGFzc3dvcmRsZXNzLmRldiIsImNyb3NzT3JpZ2luIjpmYWxzZX0\"}},\"nickname\":\"Winterfell\",\"RPID\":\"admin.passwordless.dev\",\"Origin\":\"https://admin.passwordless.dev\"}";
    public const string ValidRegisterCompleteResponse = "{\"token\":\"verify_123\"}";
}
